### PR TITLE
[FIX] [no-use-before-define] fix top level scope handling

### LINKED ISSUE #142: [no-use-before-define] false positive when exported class used in type definition
```ts
type TArrayOfTest = Array<Test>;

export class Test {}
```
leads to 

```
  1:27  error  'Test' was used before it was defined  typescript/no-use-before-define
```

with 
```json
"typescript/no-use-before-define": [
  "error", 
  {"functions": false, "typedefs": false, "classes": false}
],
```

**Note:**  without `export` it passes fine:
```ts
type TArrayOfTest = Array<Test>;

class Test {}
```

### PR DESCRIPTION
**Pull request by bradzacher**
Fixes #142

The problem was it was failing to accept the case when both the def and the var were in the top-level global/module scope

### CODE REVIEW

File: lib/rules/no-use-before-define.js [hunk 1]
```diff
@@ -39,6 +39,14 @@ function parseOptions(options) {
     return { functions, classes, variables, typedefs };
 }
 
+/**
+ * @param {Scope} scope - a scope to check
+ * @returns {boolean} `true` if the scope is toplevel
+ */
+function isToplevelScope(scope) {
```
Comment (weirdpattern) [inline lib/rules/no-use-before-define.js]: Casing of the method...

```suggestion
function isTopLevelScope(scope) {
```
